config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  root 'appointment#index'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  resources :receptions  
  resources :admins
  resources :doctors 
  resources :patients
  resources :tokens do
    resources :prescriptions
  end
  resources :payments
end

app/views/shared/_aside.html.erb
<%# <%=debugger%> 
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <img src="<%= image_url('user2-160x160.jpg') %>" class="img-circle" alt="User Image" />
      </div>
      <div class="pull-left info">
        <p><%=current_user.userable_type %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..." />
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat">
            <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    </form>

    <% if current_user.userable_type == "Reception" %>
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#"><i class="fa fa-dashboard"></i> <span>Doctors</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li class="active"><a href="<%= doctors_path %>"><i class="fa fa-circle-o"></i>Doctor(s)</a></li>
        </li>
        <li><a href="<%= new_doctor_path %>"><i class="fa fa-th"></i> <span>Doctor</span> <small class="label pull-right bg-green">new</small></a></li>

        <li class="active treeview">
          <a href="#"><i class="fa fa-dashboard"></i> <span>Patients</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li class="active"><a href="<%= patients_path %>"><i class="fa fa-circle-o"></i>  Patient(s)</a></li>
            
          </ul>
        </li>
        <li><a href="<%= new_patient_path %>"><i class="fa fa-th"></i> <span>Patient</span> <small class="label pull-right bg-green">new</small></a></li>

        <li class="active treeview">
          <a href="#"><i class="fa fa-dashboard"></i> <span>Token</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li class="active"><a href="<%= tokens_path %>"><i class="fa fa-circle-o"></i>Token(s)</a></li>
           
          </ul>
        </li>
        <li><a href="<%= new_token_path %>"><i class="fa fa-th"></i> <span>Token</span> <small class="label pull-right bg-green">new</small></a></li>
      </ul>

    <% elsif current_user.userable_type == "Doctor" %>
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#"><i class="fa fa-dashboard"></i> <span>Doctors</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li class="active"><a href="<%= doctors_path %>"><i class="fa fa-circle-o"></i> Doctor(s)</a></li>
          </ul>
        </li>
      </ul>

    <% elsif current_user.userable_type == "Patient" %>
      <ul class="sidebar-menu">
        <li class="active treeview">
          <a href="#"><i class="fa fa-dashboard"></i> <span>Patients</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li><a href="<%= patients_path %>"><i class="fa fa-circle-o"></i> Patient(s)</a></li>
          </ul>
        </li>

        <li class="active treeview">
          <a href="#"><i class="fa fa-dashboard"></i> <span>Token</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li><a href="<%= tokens_path %>"><i class="fa fa-circle-o"></i> Token(s)</a></li>
          </ul>
        </li>
        <li><a href="<%= new_token_path %>"><i class="fa fa-th"></i> <span>Token</span> <small class="label pull-right bg-green">new</small></a></li>
      </ul>
         <ul class="treeview-menu">
            <li class="active"><a href="<%= doctors_path %>"><i class="fa fa-circle-o"></i> Doctor(s)</a></li>
          </ul>
    <% end %>
  </section>
</aside>

app/views/shared/_content.html.erb
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Dashboard
            <small>Control panel</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
          </ol>
        </section>
      
        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua">
                <div class="inner">
              <% if current_user.userable_type == "Doctor" %>
                <h3>Doctor Profile</h3>
                <p>Manage Your Information</p>
              <% else %>
              <h3><%= @total_doctors %></h3>
              <p>Available Doctors</p>
              <% end %>


                </div>
                <div class="icon">
                  <i class="ion ion-bag"></i>
                </div>
                <a href="<%=doctors_path %>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
               <% if current_user.userable_type == "Patient" %>
                <h3>Patient Profile</h3>
                <p>Manage Your Details</p>
              <% else %>
             <h3><%= @total_patients %></h3>
             <p>Total Registered Patients</p>
            <% end %>

                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="<%=patients_path%>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <% if ["Patient", "Doctor"].include?(current_user.userable_type) %>
                   <h3>Token<span style="font-size: 80%;">(s)</span></h3>

                 <p>Access Your Token</p>
                  <% else %>
                 <h3><%= @total_tokens %></h3>
                <p>Total Token(s)</p>
               <% end %>

                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                <a href="<%=tokens_path%>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red">
                <div class="inner">
             <% if current_user.userable_type == "Patient" %>
              <h3>Payment<span style="font-size: 80%;">(s)</span></h3>
               <p>View Your Payments</p>
            <% else %>
           <h3><%= @total_payments %></h3>
           <p>Overall Payment Summary</p>
            <% end %>
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <a href="<%=payments_path %>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
          </div><!-- /.row -->
          <!-- Main row -->
          
      </div><!-- /.content-wrapper -->
    </section>
  </div>

app/views/shared/_footer.html.erb
 <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.0
        </div>
        <strong class="abc">Copyright &copy; 2024-2025 <a href="http://almueerstudio.com">Muneer Studio</a>.</strong> 
      </footer>
    </div><!-- ./wrapper -->

app/views/shared/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%=root_path%>" class="logo"><%=current_user&.userable_type%></a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <img src="<%= image_url('user2-160x160.jpg') %>" class="img-circle" alt="User Image"/>
                    </div>
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li><!-- end message -->
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="<%= image_url('user3-128x128.jpg') %>" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      AdminLTE Design Team
                      <small><i class="fa fa-clock-o"></i> 2 hours</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="<%= image_url('user4-128x128.jpg') %>" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Developers
                      <small><i class="fa fa-clock-o"></i> Today</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>s
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="<%= image_url('user3-128x128.jpg') %>" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Sales Department
                      <small><i class="fa fa-clock-o"></i> Yesterday</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="<%= image_url('user4-128x128.jpg') %>" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Reviewers
                      <small><i class="fa fa-clock-o"></i> 2 days</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page
                    and may cause design problems
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> 5 new members joined
                  </a>
                </li>

                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> You changed your username
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks: style can be found in dropdown.less -->
        <li class="dropdown tasks-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Create a nice theme
                      <small class="pull-right">40%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">40% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Some task I need to do
                      <small class="pull-right">60%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">60% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Make beautiful transitions
                      <small class="pull-right">80%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="<%= image_url('user2-160x160.jpg') %>" class="user-image" alt="User Image"/>
            <span class="hidden-xs">Profile</span>
          </a>
         
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="<%= image_url('user2-160x160.jpg') %>" class="img-circle" alt="User Image"/>
             
               
               <%if current_user.userable_type=="Doctor" || current_user.userable_type=="Patient" %>
               <% if current_user %>
                 <li><strong> <%= link_to current_user.userable.Name, current_user.email %></strong></li>
              <% else %>
                    <li>No user logged in</li>
                    <%end%>
                    <%else%>
              
                        <p>Reception</p>
               <% end %>

             
            </li>
            <!-- Menu Body -->
<%#             <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li> %>
            <!-- Menu Footer-->
            <%if current_user.userable_type=="Patient" %>
            <li class="user-footer">
              <div class="pull-left">


                <%=link_to "Profile",patients_path,class:"btn btn-primary"  %>
              </div>
              <div class="pull-right">
                <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>


               
              </div>
            </li>
            <%elsif current_user.userable_type=="Doctor" %>
            <li class="user-footer">
              <div class="pull-left">

                <%=link_to "Profile",doctors_path,class:"btn btn-primary"  %>
              </div>
              <div class="pull-right">
                <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>

                
              </div>
            <%elsif current_user.userable_type=="Reception" %>
            <li class="user-footer">
              <div class="pull-left">

                <%=link_to "Profile",receptions_path,class:"btn btn-primary"  %>
              </div>
              <div class="pull-right">
                 <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>

              </div> 
            <%elsif current_user.userable_type=="Admin" %>
            <li class="user-footer">
              <div class="pull-left">
                <%=link_to "Profile",admins_path,class:"btn btn-primary"  %>
              </div>
              <div class="pull-right">
                 <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>

                
              </div>             
            <%end%>
            </li>            
          </ul>
        
        </li>
      </ul>
    </div>
  </nav>
</header>


<style>
  .btn-default{
    background-color:green ;
  }
</style>