config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  root 'appointment#index'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  resources :receptions  
  resources :admins
  resources :doctors 
  resources :patients
  resources :tokens do
    resources :prescriptions
  end
  resources :payments
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  has_one :payment, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  accepts_nested_attributes_for :prescriptions, reject_if: :all_blank, allow_destroy: true
  # enum status: { pending: 0, completed: 1, failed: 2, refunded: 3, canceled: 4 }
  enum status: [:pending, :completed, :failed, :refunded, :canceled]
before_save :set_status_based_on_payment

def set_status_based_on_payment
      if payment&.status == "completed"
         self.status = :completed
      elsif payment&.status == "failed"
         self.status = :failed
      elsif payment&.status == "refunded"
       self.status = :refunded
      else
       self.status = :pending
     end
   end


end

# has many through Association ...............

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  def index
    if current_user.userable_type == "Doctor"
      current_doctor = current_user.userable
      @tokens = current_doctor.tokens

    elsif current_user.userable_type == "Patient"
      current_patient = current_user.userable
      @tokens = current_patient.tokens

    elsif current_user.userable_type == "Reception" || current_user.userable_type == "Admin"
      @tokens = Token.all

    else
      @tokens = []
    end
  end

  def new
    @token = Token.new
  end

  def create
    @token = Token.new(Blood_pressure: params[:token][:Blood_pressure],
                       Temperature: params[:token][:Temperature],
                       Weight: params[:token][:Weight],
                       doctor_id: params[:token][:doctor_id],
                       patient_id: params[:token][:patient_id],
                       status: params[:token][:status])

    if @token.save
      redirect_to tokens_path, notice: 'Create was successfully created!!......'
    else
      render :new
    end
  end

  def show
    @token = Token.find(params[:id])
    authorize(@token)

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def edit
    @token = Token.find(params[:id])
  end

  def update
    @token = Token.find(params[:id])
    if @token.update(params_token)
      redirect_to tokens_path, notice: 'Token was successfully Updated!!...  '
    else
      render :edit
    end
  end

  def print
    @token = Token.find(params[:id])
  end

  def destroy
    @token = Token.find(params[:id])
    if @token.destroy(params_token)
      redirect_to tokens_path, notice: 'Token was successfully Updated!!...  '
    else
      render :all
    end
  end

  private

  def params_token
    params.require(:token).permit(:Blood_pressure, :Temperature, :Weight, :doctor_id, :patient_id, :status)
  end
end

app/views/tokens/_form.html.erb
<%= form_with model: @token do |form| %>
  <div class="content-body">
    <div class="row">
      <div class="col-lg-5">
        <div class="form-group">
          <%= form.label :Blood_pressure, class: 'mb-3' %>
          <%= form.text_field :Blood_pressure, class: 'form-control form-control-lg' %>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="form-group">
          <%= form.label :Temperature, class: 'mb-3' %>
          <%= form.text_field :Temperature, class: 'form-control form-control-lg' %>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="form-group">
          <%= form.label :Weight, class: 'mb-3' %>
          <%= form.text_field :Weight, class: 'form-control form-control-lg' %>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="form-group">
          <%= form.label :doctor_id, "Select Doctor", class: 'mb-3' %>
          <%= form.select :doctor_id, options_from_collection_for_select(Doctor.all, :id, ->(d) { "#{d.Name} - #{d.Specialization}" }), { prompt: "Choose a doctor" }, class: "form-control form-control-lg" %>
        </div>
      </div>

      <% if current_user.userable_type == "Patient" %>
        <%= form.hidden_field :patient_id, value: current_user.userable.id %>

      <% elsif current_user.userable_type == "Reception" || current_user.userable_type == "Admin" %>
        <div class="col-lg-5">
          <div class="form-group">
            <%= form.label :Patient_id, "Select Patient", class: 'mb-3' %>
            <%= form.select :patient_id, options_from_collection_for_select(Patient.all, :id, ->(d) { "#{d.id} - #{d.Name}" }), { prompt: "Choose a patient" }, class: "form-control form-control-lg" %>
          </div>
        </div>
      <% end %>
      <div class="col-lg-5">
        <%= form.submit class: 'btn btn-primary btn-lg' %>
        <%= link_to 'Back to Token', tokens_path, class: 'btn btn-primary btn-lg' %>

      </div>
    </div>
  </div>
<% end %>
<style type="text/css">
    .content-body {
        margin-left: 120px;
    }
</style>

app/views/tokens/edit.html.erb
<div class="col-lg-12">
	<div class="card">
		<div class="card-body">
			<h1 class="text-center">Update Token</h1>
		</div>	
	</div>
	<%=render 'form',token:@token %>
</div> 

app/views/tokens/index.html.erb
<div class="content-body">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h1 class="text-center">Token Infermation</h1>
      </div>
      <p class="notice"><%= notice %></p>
    </div>
    <% if current_user.userable_type == "Reception" || current_user.userable_type == "Patient" ||
      current_user.userable_type == "Admin" %>
      <div class="abc">
        <%= link_to 'New token', new_token_path, class: 'btn btn-primary btn-lg' %>
      </div>
    <% end %>
  </div>
<table id="example" class="display" style="width:100%">
  <thead>
    <tr>
      <th>ID</th>
      <th>Blood Pressure</th>
      <th>Temperature</th>
      <th>Weight</th>
      <th>Doctor</th>
      <th>Patient</th>
      <th>Payment Status</th>
      <th>Payment Type</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.id %></td>
        <td><%= token.Blood_pressure %> mmHg</td>
        <td><%= token.Temperature %> °F</td>
        <td><%= token.Weight %> kg</td>
        <td>
          <a href="<%= doctor_path(token.doctor.id) %>">
            <%= token.doctor_id %>#<%= token.doctor.Name %>
          </a>
        </td>
        <td>
          <a href="<%= patient_path(token.patient.id) %>">
            <%= token.patient_id %>#<%= token.patient.Name %>
          </a>
        </td>
        <td>
          <% if token.payment.present? %>
            <span class="badge <%= status_label_class(token.payment.status)  if token.payment.present?%>">
              <%# <%= token.payment.status %> 
              <p>Paid</p>
              <%else%>

              <strong class="lead">Padding</strong>
            </span>
          <%end%>
        </td>
        <td>
          <% if token.payment.present? %>
            <%=token.payment.payment_type%>
          <%end%>
      
        </td>
        <td>
          <% if current_user.userable_type == "Reception" || current_user.userable_type == "Patient" || current_user.userable_type == "Admin" %>
            <%= link_to "Make Payment", new_payment_path(token_id: token.id), class: "btn btn-success btn-sm" %>
          <% end %>

          <% if current_user.userable_type == "Doctor" %>
          <%= link_to "Edit", edit_token_path(token), class: 'btn btn-info btn-sm' %>
            <%= link_to 'Show', token_path(token), class: 'btn btn-primary btn-sm' %>
            <%= link_to "Prescriptions", new_token_prescription_path(token.id), class: "btn btn-success btn-sm" %>
          <% elsif current_user.userable_type == "Patient" || current_user.userable_type == "Reception" %>
            <%= link_to "Edit", edit_token_path(token), class: 'btn btn-info btn-sm' %>
            <%= link_to "Print", token_path(token, format: :pdf), class: "btn btn-primary btn-sm" %>
            <%= link_to 'Delete', token_path(token), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            <%= link_to 'Show', token_path(token), class: 'btn btn-primary btn-sm' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



    </div>

    </div>
    <style>

        .abc {
            padding: 34px;
        }

        .search_bar {
            position: relative;
            left: 500px;
            top: 10px;
        }

        .content-body {
            margin-left: 150px;
        }
       .lead{
        background-color:green;
        color: white;
             
       }
    </style>



    <script type="text/javascript" src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>

    <script type="text/javascript">

      new DataTable('#example');
    </script>

app/views/tokens/new.html.erb
<div class="col-lg-12">
	<div class="card">
		<div class="card-body">
			<h1 class="text-center">Create New Token</h1>
		</div>	
	</div>
	<%= render "form" %>
</div> 

app/views/tokens/show.html.erb
<div class="col-lg-12">
	<div class="card">
		<div class="card-body">
			<h1 class="text-center">Token Detial</h1>
		</div>	
	</div>
	<p class="lead"><strong>Blood_pressure => </strong><%=@token.Blood_pressure %> </p>
	<p class="lead"><strong>Temperature => </strong><%=@token.Temperature %> </p>
	<p class="lead"><strong>Weight => </strong><%=@token.Weight%> </p>
	<p class="lead"><strong>doctor => </strong><%=@token.doctor_id %> </p>
	<p class="lead"><strong>Patien => </strong><%=@token.patient_id%> </p>
	
	<%=link_to 'Back to Token',tokens_path,class:'btn btn-primary btn-lg ' %>
	<%=link_to 'Edit Token',edit_token_path,class:'btn btn-info btn-lg ' %>
	</div>

app/views/tokens/show.pdf.erb
<div class="card">
  <div class="card-header">
    <h1 class="text-center">Token Information</h1>
  </div>
  <div class="card-body">
    <table class="table table-borderd">
      <thead>
      <tr>
        <th>Name:</th>
        <td><%= @token.patient.Name %></td>
        <th>CNIC:</th>
        <td><%= @token.patient.CNIC %></td>
        <th>Gender:</th>
        <td><%= @token.patient.Gender %></td>
      </tr>
      <tr>
        <th>Address:</th>
        <td><%= @token.patient.Address %></td>
        <th>Phone:</th>
        <td><%= @token.patient.PhoneNo %></td>
        <th>Age:</th>
        <td><%= ((Time.zone.now - @token.patient.date_of_birth.to_time) / 1.year.seconds).to_i if @token.patient.date_of_birth %></td>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th>Blood Pressure:</th>
        <td><%= @token.Blood_pressure %></td>

        <th>Temperature:</th>
        <td><%= @token.Temperature %></td>

        <th>Weight:</th>
        <td><%= @token.Weight %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>



<style type="text/css">
    .table {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        line-height: 40px;


    }

    .card {
        border: 2px solid #ddd;
        background-color: #f9f9f9;
    }

    .card-body {
        border: 1px solid #ddd;
    }

    .text-center {
        text-align: center;
    }


</style>