config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  root 'appointment#index'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  resources :receptions  
  resources :admins
  resources :doctors 
  resources :patients
  resources :tokens do
    resources :prescriptions
  end
  resources :payments
end

app/models/reception.rb
class Reception < ApplicationRecord
	validates :email, presence:true, uniqueness:true
	validates :phoneno, presence:true, uniqueness:true
	has_one :user, as: :userable ,dependent: :destroy

	after_create :set_devise_user
	def set_devise_user
		self.create_user(email:self.email,password:"123456")
	end
end

	

app/controllers/receptions_controller.rb
class ReceptionsController<ApplicationController
	def index
		@receptions=Reception.all
	end
	def new
		@reception=Reception.new
	end
	def create
		@reception=Reception.new(Name: params[:reception][:Name],
			email: params[:reception][:email],
			phoneno: params[:reception][:phoneno],
			address: params[:reception][:address])
		if @reception.save
			redirect_to receptions_path, notice:'Reception has been successfully created!'
		else
			render :new
		end
	end
	def edit
		@reception=Reception.find(params[:id])
	end
	def update
		@reception=Reception.find(params[:id])
		if @reception.update(params_reception)
			redirect_to receptions_path,	notice:'Reception has been successfully Updated!'
		else 
			render :edit
		end
	end
	def show
		@reception=Reception.find(params[:id])
	end
	private
	def params_reception
		params.require(:reception).permit(:Name,:email,:phoneno, :address)
	end

end

app/views/receptions/_form.html.erb
<%=form_with model: @receptions do |form| %>
<div class="col-lg-5">
	<div class="col-lg-5">
		<div class="form-group">
			<%=form.label :Name, class:'mb-3' %>
			<%=form.text_field :Name, class:'form-control form-control-lg' %>
		</div>
	</div>
</div>
<div class="col-lg-5">
	<div class="col-lg-5">
		<div class="form-group">
			<%=form.label :Email, class:'mb-3' %>
			<%=form.text_field :email, class:'form-control form-control-lg' %>
		</div>
	</div>
</div>
<div class="col-lg-5">
	<div class="col-lg-5">
		<div class="form-group">
			<%=form.label :ContectNo, class:'mb-3' %>
			<%=form.text_field :phoneno, class:'form-control form-control-lg' %>
		</div>
	</div>
</div>
<div class="col-lg-5">
	<div class="col-lg-5">
		<div class="form-group">
			<%=form.label :Address, class:'mb-3' %>
			<%=form.text_field :address, class:'form-control form-control-lg' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-5">
         <div class="form-group">
         	<%=form.submit class:"btn btn-primary btn-lg" %>
         	<%=link_to "Back To Reception", receptions_path,class:"btn btn-info btn-lg" %>
         </div>
    </div>
</div>

<%end%>

app/views/receptions/edit.html.erb
<div class="card">
	<div class="card-body">
		<h1 class="text-center">Reception Update </h1>
	</div>
	<%=render 'form',reception:@reception %>
</div>

app/views/receptions/index.html.erb
<div class="col-lg-5">
	<div class="card">
		<div class="card-body">
			<h1 class="text-center">Reception Infermation</h1>
		</div>
		<%=link_to "New Reception",new_reception_path,class:"btn btn-info btn-lg" %>
	</div>
	<table class="table-border table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Email</th>
				<th>ContectNo</th>
				<th>Address</th>
			</tr>
		</thead>
		<tbody>
			<%@receptions.each do |reception|%>
			<tr>
				<td><%=reception.id%></td>
				<td><%=reception.Name%></td>
				<td><%=reception.email%></td>
				<td><%=reception.phoneno%></td>
				<th><%=reception.address %></th>
				<th>
					<%=link_to "Edit",edit_reception_path(reception),class:"btn btn-primary btn-lg" %>
					<%=link_to "Show",reception_path(reception),class:"btn btn-info btn-lg" %>
				</th>
			</tr>
			<%end%>
		</tbody>
	</table>
</div>

app/views/receptions/new.html.erb
<div class="card">
	<div class="card-body">
		<h1 class="text-center">New Reception</h1>
	</div>
	<%= render  'form',reception:@reception %>
</div>