config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  root 'appointment#index'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  resources :receptions  
  resources :admins
  resources :doctors 
  resources :patients
  resources :tokens do
    resources :prescriptions
  end
  resources :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  
  belongs_to :token
  validates  :amount, :detail, presence:true
  enum :status, [:pending, :paid, :refunded]
  enum :payment_type, [:cash, :jazz_cash, :easy_passa]
  # enum :method, { cash: 0, credit_card: 1, debit_card: 2, online: 3, insurance: 4 }

end

app/controllers/payments_controller.rb
class PaymentsController<ApplicationController
	 def index
        if current_user.userable_type == "Patient"

       current_patient = current_user.userable
       @payments = current_patient.payments
    else
      @payments = Payment.all
    end
  end
	def new
		@payment=Payment.new
	end
	def create
		@payment=Payment.new(amount: params[:payment][:amount],
			payment_type: params[:payment][:payment_type],
			status: params[:payment][:status],
			detail: params[:payment][:detail],
			token_id: params[:payment][:token_id])
		if @payment.save
			redirect_to tokens_path,notice:"patients has been successfully payment"
		else
			render :new
		end
	end
	def show
		@payment=Payment.find(params[:id])
	end
	def edit
		@payment=Payment.find(params[:id])
	end
	def update
		@payment=Payment.find(params[:id])
		if @payment.update(parmas_payment)
			redirect_to payments_path
		else
			render :edit
		end
	end

private
def parmas_payment
	params.require(:payment).permit(:amount,:payment_type,:detail,:token_id, :status)
end
end

app/views/payments/_form.html.erb
<%= form_with model: @payment do |form| %>
  <div class="row">
    <div class="col-lg-5">
      <div class="form-group">
        <%= form.label :Amount, class: 'mb-3' %>
        <%= form.text_field :amount, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="col-lg-5">
      <div class="form-group">
        <%= form.label :Payment_type, class: 'mb-3' %>
        <%= form.select :payent_type, options_for_select(Payment.payment_types.keys), {}, class: 'form-control form-control-lg' %>
        <%#=form.text_field :payment_type, class:'form-control form-control-lg' %>
      </div>
    </div>
    <div class="col-lg-5">
      <div class="form-group">
        <%= form.label :Details, class: 'mb-3' %>
        <%= form.text_field :detail, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <% if current_user.userable_type == "Patient" %>

      <%= form.hidden_field :token_id, class: 'form-control form-control-lg', value: params[:token_id] %>
    <% elsif current_user.userable_type == "Reception" %>
      <div class="col-lg-5">
        <div class="form-group">
          <%= form.label :token_id, "Select token_id", class: 'mb-3' %>
          <%= form.select :token_id, options_from_collection_for_select(Token.all, :id, ->(d) { "#{d.id} - #{d.patient.Name}" }), { prompt: "Choose a token_id + Patient_Name" }, class: "form-control form-control-lg" %>


        </div>
      </div>
    <% end %>

    <div class="col-lg-5">

      <%= form.submit class: 'abc btn btn-primaty btn-lg' %>
      <%= link_to "Back Payment", payments_path, class: 'ab btn btn-primaty btn-lg' %>

    </div>

<% end %>

<style type="text/css">
    .abc {
        background-color: #7CFC00;
    }

    .ab {
        background-color: #FFFF00;
    }
</style>

app/views/payments/edit.html.erb
<div class="col-lg-12">
	<div class="card">
		<div class="card-body">
			<h1 class="text-center">Payment Update</h1>
		</div>
	</div>
	<%=render 'form',payment:@payment %>
</div>		

app/views/payments/index.html.erb
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <h1 class="text-center">Payment Infermation</h1>
      <% if current_user.userable_type == "Reception" %>
        </div>
        <%= link_to "New payment", new_payment_path, class: 'btn btn-primaty btn-lg' %>
      <% elsif current_user.userable_type == "Patient" %>
        <%= link_to "New payment", new_payment_path, class: 'btn btn-primaty btn-lg' %>
      <% else %>
      <% end %>
      <table class="table table-header">
        <thead>
        <tr>
          <th>ID</th>
          <th>Amount</th>
          <th>Payment_type</th>
          <th>Details</th>

          <th>Token</th>
        </tr>
        </thead>
        <tbody>
        <% @payments.each do |payment| %>
          <tr>
            <td><%= payment.id %></td>
            <td><%= payment.amount %></td>
            <td><%= payment.payment_type %></td>
            <td><%= payment.detail %></td>

            <td><%= payment.token_id %></td>
            <td>
              <% if current_user.userable_type == "Reception" %>
                <%= link_to "Show", payment_path(payment), class: 'abc btn btn-primaty btn-lg' %>
                <%= link_to "Edit", edit_payment_path(payment), class: 'btn btn-primaty btn-lg' %>
                <%= link_to "Delete", payment_path(payment), class: 'ab btn btn-primaty btn-lg' %>
              <% elsif current_user.userable_type == "Patient" %>
                <%= link_to "Show", payment_path(payment), class: 'abc btn btn-primaty btn-lg' %>
                <%= link_to "Edit", edit_payment_path(payment), class: 'btn btn-primaty btn-lg' %>
                <%= link_to "Delete", payment_path(payment), class: 'ab btn btn-primaty btn-lg' %>
              <% else %>
                <%= link_to "Show", payment_path(payment), class: 'abc btn btn-primaty btn-lg' %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
</div>
<style type="text/css">
    .btn {
        color: white;
        font: bold;
        background-color: #1959;
    }

    .abc {
        color: white;
        font: bold;
        background-color: rgb(8, 116, 200);
    }

    .ab {
        color: white;
        font: bold;
        background-color: rgb(80, 96, 240);
    }


</style>

app/views/payments/new.html.erb
<div class="col-lg-12">
	<div class="card">
		<div class="card-body">
			<h1 class="text-center">Payment Infermation</h1>
		</div>
	</div>
	<%=render 'form',payment:@payment %>
</div>		

app/views/payments/show.html.erb
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <h1 class="text-center">Payment Detial</h1>
    </div>
  </div>
  <p class="lead"><strong>ID = </strong><%= @payment.id %> </p>
  <p class="lead"><strong>Amount = </strong><%= @payment.amount %> </p>
  <p class="lead"><strong>Payment_type = </strong><%= @payment.payment_type %> </p>
  <p class="lead"><strong>Detail = </strong><%= @payment.detail %> </p>

  <%= link_to 'Back to patient', payments_path, class: 'btn btn-primary btn-lg ' %>
  <%= link_to 'Edit patient', edit_payment_path, class: 'btn btn-info btn-lg ' %>
</div>